QueteRazor/Models/ErrorViewModel.cs
namespace QueteRazor.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

QueteRazor/Models/ExpenditureModel.cs
namespace QueteRazor.Models
{
    public class ExpenditureModel
    {
        public string Name { get; set; }
        public DateTime Date { get; set; }
        public double Price { get; set; }

    }
}

QueteRazor/Controllers/ExpenditureController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QueteRazor.Models;

namespace QueteRazor.Controllers
{
    public class ExpenditureController : Controller
    {
        // GET: ExpenditureController
        public ActionResult Index()
        {
            return View(GetExpenditureModels());
        }

        // GET: ExpenditureController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        private IEnumerable<ExpenditureModel> GetExpenditureModels()
        {
            List<ExpenditureModel> expenditureModels = new List<ExpenditureModel>();
            expenditureModels.Add(new ExpenditureModel { Date = DateTime.Now , Name = "Toto" , Price = 100.0});
            expenditureModels.Add(new ExpenditureModel { Date = DateTime.Now, Name = "Toto 1", Price = 110.0 });
            expenditureModels.Add(new ExpenditureModel { Date = DateTime.Now, Name = "Toto 2", Price = 120.0 });
            return expenditureModels;
        }

       
    }
}

QueteRazor/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QueteRazor.Models;
using System.Diagnostics;

namespace QueteRazor.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

QueteRazor/Views/Expenditure/Index.cshtml
@model IEnumerable<QueteRazor.Models.ExpenditureModel>

@{
    ViewData["Title"] = "Expenditutre";
    var total = Model.Sum(item => item.Price);
}

<h1>Expenditure</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Date)
            </th> 
            <th>
                @Html.DisplayNameFor(model => model.First().Price)
            </th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
        
        </tr>
    }
    </tbody>
</table>

<h1>Total: @total € </h1>

QueteRazor/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

QueteRazor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QueteRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QueteRazor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QueteRazor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expenditure" asp-action="Index">Expenditure</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - QueteRazor - <a asp-area="" asp-controller="Expenditure" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>